### PR TITLE
Build system cleanups (mostly)

### PR DESCRIPTION
**Pull request by wferi**
Hi,
Preparing to include your fork in the Debian package of pam-mysql I found a couple of issues with the build system and the repo structure. There are no actual code changes in this pull request.
Would you please consider this?
Thanks,
Feri.

### CODE REVIEW

**Comment by NigelCunningham** [comment]
Looks good; thanks.

I've had a few attempts at using autotools over the years, and always struggled to find good documentation. It looks like you understand them really well so I'm wondering if you'd be willing to give me a pointer to something that will help me do a better job of maintaining that part of the package.

**Comment by wferi** [comment]
The starting point is the official documentation distributed with Autoconf and Automake, available via `info autoconf` and `info automake` but also available [online](https://www.gnu.org/software/autoconf/manual/). Beyond that I find the [Autotools Mythbuster](https://autotools.io/index.html) fairly good, especially regarding pkg-config.

Concerning this pull request, I forgot to mention that the bootstrap procedure now consists of `autoreconf -f -i` (pretty standard) and `./configure`. Then `make distcheck` creates a proper distributable and also checks it. This is what you should attach to the eventual release on GitHub or publish elsewhere, along with its detached GPG signature. That's usually better than a plain tag (although it's possible to check signatures on tags as well).

**Comment by NigelCunningham** [comment]
Thanks for those references - I've come across all of those before; perhaps I just need to work through them systematically rather than treating them as references.

I'm going to seek to test this and merge today. Sorry for the delay!

**Comment by NigelCunningham** [comment]
"Actually," he said, "let's just get it out of the way now." And it only took a minute.

Thanks!

**Comment by wferi** [comment]
Thank you for merging! By the way, have you got any plans about making a release? It would be nice if you met the Debian freeze: we could then ship a proper release in squeeze instead of some Git snapshot.
And yes, the Autotools manuals aren't exactly an easy read, but having a good grasp of the introductory chapters makes the reference materials much more useful.

**Pull request merged**
